// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebScrappinDemo.Migrations
{
    [DbContext(typeof(UniDbContext))]
    [Migration("20260612111843_ModeloRelacional1")]
    partial class ModeloRelacional1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Centro")
                        .HasColumnType("TEXT");

                    b.Property<string>("CentroInvestigación")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Docentia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoDocente")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoInvestigación")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quinquenios")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SexeniosInvestigación")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SexeniosTransferencia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TieneBiografia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlPerfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("DocenteProyecto", b =>
                {
                    b.Property<int>("DocentesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DocentesId", "ProyectosId");

                    b.HasIndex("ProyectosId");

                    b.ToTable("DocenteProyecto");
                });

            modelBuilder.Entity("Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colaboradores")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadFinanciadora")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaFinal")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvPrincipales")
                        .HasColumnType("TEXT");

                    b.Property<string>("Investigadores")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestigadoresTecnicos")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefExterna")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefInterna")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("DocenteProyecto", b =>
                {
                    b.HasOne("Docente", null)
                        .WithMany()
                        .HasForeignKey("DocentesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
