// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebScrappinDemo.Migrations
{
    [DbContext(typeof(UniDbContext))]
    [Migration("20260610111327_RefactorBiografiaYNuevosgrupos")]
    partial class RefactorBiografiaYNuevosgrupos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Centro")
                        .HasColumnType("TEXT");

                    b.Property<string>("CentroInvestigación")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Docentia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoDocente")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoInvestigación")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quinquenios")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SexeniosInvestigación")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SexeniosTransferencia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TieneBiografia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlPerfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Docentes");
                });
#pragma warning restore 612, 618
        }
    }
}
